modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="megamodmain"
version="1.0.0"
displayName="MegaModMain"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="GERARD, MCreator"

[[dependencies.megamodmain]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




